---
# handlers file for webserver
- name: firewall reload
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded

- name: httpd restart
  ansible.builtin.systemd:
    name: httpd
    state: restarted
