---
- hosts: domainmember
  vars:
    domain: ansible.local

  tasks:
  - name: Domain Join
    win_domain_membership:
      dns_domain_name: "{{ domain }}"
      domain_admin_user: "{{ ansible_user }}@{{ domain }}"
      domain_admin_password: "{{ ansible_password }}"
      state: domain
    register: domain_join

  - name: Reboot Server
    win_reboot:
    when: domain_join.reboot_required