---
- hosts: linuxservers
  become: yes

  vars:
      package:
          - httpd
          - mariadb-server
          - php
          - php-mysqlnd

  tasks:
  - name: Install Packages
    ansible.builtin.package:
      name: "{{ package }}"
      state: latest