---
- hosts: windowsservers
  collections:
    - ansible.windows
  vars_files:
    - ~/secret.yml
  vars:
    ansible_password: "{{ windows_password }}"
  tasks:
  - name: Install IIS (Web-Server only)
    win_feature:
      name: Web-Server
      state: present